name: CTSuiteBukkit
main: de.crafttogether.ctsuite.bukkit.CTSuite
version: 1.0
website: http://www.craft-together.de
author: J0schlZ
description: An essential plugin for BungeeCord
depend: [Vault, Multiverse-Core]
softdepend: [Sockets4MC, Kotlin4MC]
commands:
   fly:
     description: Toggle Flymode
     usage: /fly [on/off/player] [on/off]
   gamemode:
     description: Change Gamemode
     usage: /gamemode <gamemode> [player]
     alias: [gm]
   tp:
     description: Teleports you to another player
     usage: /tp <player>
   tphere:
     description: Teleports another player to you
     usage: /tphere <player>
   tppos:
     description: Teleports you to a location
     usage: /tppos <x> <y> <z> [world] [server] [pitch] [yaw]